name: PR Preview Test Runner
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [issue_comment]
jobs:
  show-event:
    if: ${{github.event.comment.user.login == 'atlas-by-wp-engine[bot]' && contains(github.event.comment.body, ':white_check_mark:')}}
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WORDPRESS_URL: https://faustintl.wpengine.com/
    outputs:
      output1: ${{ steps.regex-match.outputs.match }}
    steps:
      - uses: actions-ecosystem/action-regex-match@v2.0.2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: 'https:\/\/[a-z0-9]{25}\.js\.wpenginepowered.com'
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            We're testing your Atlas stuff here:
            ---

            ${{ steps.regex-match.outputs.match }}

            ---
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v5 # use the explicit version number
        env:
          CYPRESS_BASE_URL: ${{ steps.regex-match.outputs.match }}
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            We're done testing your Atlas stuff. Here are the results:
            ${{ steps.cypress.outcome }}


