name: ci
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [issue_comment]
jobs:
  show-event:
    if: ${{github.event.comment.user.login == 'atlas-by-wp-engine[bot]' && contains(github.event.comment.body, ':white_check_mark:')}}
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT" >> "$GITHUB_OUTPUT"
  echo-url:
    needs: show-event
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT: ${{needs.show-event.outputs.output1}}
        run: echo "$OUTPUT"

